# Jekyll configuration

title: "Max Azarcon"
description: "Designer. Developer. Occasional air‑hockey menace."
url: "" # deployed URL
markdown: kramdown

plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path/
